csvengine/csvmeta/csvmeta_blueprint.py
'''
Created on Dec 24, 2015

@author: jumbrich
'''

from flask import Blueprint, render_template,current_app

from flask import Flask, request, redirect, url_for


from werkzeug.exceptions import RequestEntityTooLarge

from csvengine.datacache.error_handler import ErrorHandler as eh

import structlog
from csvengine.data_cache import DataCache
from csvengine.csvmeta.csvw_json import CSVMCreator
from flask.json import jsonify
log =structlog.get_logger()


csvm_bp = Blueprint('csvm', __name__,
                    template_folder='templates',
                    static_folder='static',
                    )


def decode_utf8(string):
    if isinstance(string, str):
        for encoding in (('utf-8',), ('windows-1252',), ('utf-8', 'ignore')):
            try:
                return string.decode(*encoding)
            except:
                pass
        return string # Don't know how to handle it...
    return unicode(string, 'utf-8')

def my_render_template(templ, **kwargs):
    return render_template(templ,  navigation_bar=current_app.config['navigation_bar'], **kwargs)

@csvm_bp.route('/csvm/editor/service')
def csvmeditor_service():
    fileID = request.args.get("fileID")
    url = request.args.get("url")

    datacache = current_app.config['DATACACHE']
    
    # TODO use URL for getting file
    if not fileID and url:
        fileID = datacache.getFileName(url)
    if not fileID:
        data={
              "message": 'Arguments missing: fileID required',
              'title':"Input Error",
              'exception': "",
              "filename": "No CSV file specified"
        }
        return render_template("input_error.html", **data)

    # current_app.logger.debug("Reading "+fileID+" from disk:"+datacache.submit_folder[folder])
    # table = datacache.getParser(fileID,folder=datacache.submit_folder[folder])
    current_app.logger.debug("Reading "+fileID+" from disk")
    table = datacache.getParser(fileID, original=True)

    title = url if url else fileID
    original = datacache.getSubmit(fileID)
    rows = len(original.split('\n'))
    results={ 'orig': decode_utf8(original), 'table': table.__dict__, 'title': title, 'cols': table.columns, 'rows': rows}

    #d= decode_utf8(data)
    #results={'orig':decode_utf8(original),'cleaned': table.generate().decode('utf-8'), 'table':table.__dict__}

    import datetime
    #sets the variable "today" as the datetime object.
    
    today = datetime.datetime.today()
    results['time']=today.strftime('%Y-%m-%d')
    if url:
        results['url']=url
    return my_render_template("csvm_editor_result.html", data=results)

@csvm_bp.route('/createcsvm', methods=['POST'])
def createcsvm_service():
    meta= CSVMCreator.create(request.form)
    resp = jsonify(meta)
    resp.status_code = 200
    return resp
    
@csvm_bp.route("/csvm/editor")
def csvmeditor():
    return my_render_template("csvm_editor.html")



@csvm_bp.route("/csvm/validator")
def csvmval():
    return my_render_template("csvm_val.html")

csvengine/datacache/datacache_blueprint.py
'''
Created on Dec 24, 2015

@author: jumbrich
'''

from flask import Blueprint, render_template,current_app

from flask import request, redirect, url_for

from werkzeug.exceptions import RequestEntityTooLarge

from csvengine.datacache.error_handler import ErrorHandler as eh

import structlog
from flask.helpers import make_response


log =structlog.get_logger()


datacache_bp = Blueprint('datacache', __name__,
                    template_folder='templates',
                    static_folder='static',
                    )


### HELPER FUNCTIONS
####################
ALLOWED_EXTENSIONS = set(['csv'])

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

def decode_utf8(string):
    if isinstance(string, str):
        for encoding in (('utf-8',), ('windows-1252',), ('utf-8', 'ignore')):
            try:
                return string.decode(*encoding)
            except:
                pass
        return string # Don't know how to handle it...
    return unicode(string, 'utf-8')


### SUBMIT 
##########
@datacache_bp.route('/submit', methods=['POST'])
def submit():
    file, url, filename = None, None, ''
    try:
        #debug print
        current_app.logger.debug(request.form)
        service = request.form.get('service')

        ### CHECK INPUT PARAMETERS
        ###########################
        
        #check for url
        url = request.form.get('url')

        #check for file uploads
        file = request.files['uploadBtn']
        fileID = request.form.get('fileID')
        if file and file.filename != '':
            filename = file.filename
        elif url:
            filename = url
        else:
            filename = fileID

        #check for copy paste
        textUpload = request.form.get('textUpload')

        #debug
        #current_app.logger.debug('textUpload:'+textUpload+" url:"+url+" fileID:"+fileID+" file:"+file.filename)

        # don't store data checkbox
        store_data = 'check' not in request.form

        datacache = current_app.config['DATACACHE']

        # error handling
        if file and not allowed_file(file.filename):
            data={
              "message":'"'+filename+'" is not a valid filename.',
              'title':"Format Error",
              'exception': ValueError.__class__.__name__,
              "filename": filename
              }
            
            return render_template("input_error.html", **data)
        if fileID:
            if not datacache.exists(fileID):
                data={
                      "message":"Unfortunately we cannot find your file with the ID "+fileID+". Please re-submit the file or URL.",
                      'title':"File not found",
                      'exception': ValueError.__class__.__name__,
                      "filename": filename
                      }
                return render_template("input_error.html", **data)

        if url or (file and file.filename != '') or textUpload:
            # store content in web or tmp folder
            if store_data:
                fileID = datacache.submitToWeb(file=file, url=url, content=textUpload)
            else:
                fileID = datacache.submitToTmp(file=file, url=url, content=textUpload)
            # set parameter in URL
            if url and fileID:
                return redirect(url_for(service, url=url, fileID=fileID))
            else:
                return redirect(url_for(service, fileID=fileID))

        # error if no input is specified
        data={
              "message": 'Arguments missing: fileID or url required',
              'title':"Input Error",
              'exception': "",
              "filename": "No CSV file specified"
        }
        return render_template("input_error.html", **data)

    except RequestEntityTooLarge as e:
        max_in_mb = current_app.config['MAX_CONTENT_LENGTH']/1000000.0
        data={
              "message":'The file '+filename+' exceeds the capacity limit of '+str(max_in_mb)+' MB.',
              'title':"Input File Too Large",
              'exception': e.__class__.__name__,
              "filename": filename
        }
        return render_template("input_error.html", **data)
    except Exception as e:
        eh.handleError(log, "Error", exception=e)
        
        data={
              "message":e.message,
              'title':"Submit Error",
              'exception': e.__class__.__name__,
              "filename": filename
        }
        return render_template("input_error.html", **data )

### method for downloading CSV file
@datacache_bp.route('/get/cleaned', methods=['GET', 'POST'])
def get_cleand_file():
    fileID = request.args.get("fileID")
    url = request.args.get("url")
    
    datacache = current_app.config['DATACACHE']
    
    if not fileID and url:
        fileID = datacache.getFileName(url)
    if not fileID:
        data={
              "message": 'Arguments missing: fileID required',
              'title':"Input Error",
              'exception': "",
              "filename": "No CSV file specified"
        }
        return render_template("input_error.html", **data)
    
    table = datacache.getParser(fileID)
    
    output = make_response(table.generate())
    output.headers["Content-Disposition"] = "attachment; filename="+fileID+".csv"
    output.headers["Content-type"] = "text/csv"
    return output

csvengine/templates/about.html
{% extends "base.html" %} {% block title %}About{% endblock %}
{% set active_page = "index" -%}
{% block content %}
     <!-- Your content goes here -->
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--1-col"></div>
            <div class="mdl-cell mdl-cell--10-col">
                <div class="mdl-card mdl-cell mdl-cell--12-col">
                    <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
                        <h2 class="mdl-card__title-text">About</h2>
                    </div>

                    <div class="mdl-card__supporting-text">
                        <p>
                            The <b>CSV Engine</b> is a project by the <a href="http://ai.wu.ac.at/">Institute for Information Business</a>
                            at WU Vienna (<a href="http://wu.ac.at/">Vienna University of Economics and Business</a>).
                            It is a collection of tools and services for processing and enriching CSV files.

                        </p>
                        <p>
                            This is a research project and we try to add more features and fix bugs.
                            Any feedback, bug reports, and other comments are very welcome.
                            Please use the following email address for contact: <br/><b>contact (at) data.wu.ac.at</b>
                        </p>

                        <h5>CSV Engine team:</h5>
                        <ul>
                            <li>Jürgen Umbrich</li>
                            <li>Sebastian Neumaier</li>
                            <li>Axel Polleres</li>
                        </ul>

                        <h5>About the Services</h5>
                        <ul>
                            <li class=" mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
                                The <a href="{{ url_for('ui.csvclean') }}">CSV Clean</a> service is based on
                                <a href="https://github.com/sebneu/anycsv">anycsv</a>, a simple and robust CSV parser.
                            </li>

                            <li class=" mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
                                The <a href="{{ url_for('ui.csvmeditor') }}">CSV Metadata generator</a>, by Manuel Undesser,
                                was developed in the course of a Bachelor thesis at WU Vienna.
                                The metadata is compliant with the <a href="https://www.w3.org/2013/csvw/wiki/Main_Page">CSV on the Web metadata specification</a>.
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>



 {% endblock %}

csvengine/templates/base.html
<!doctype html>
<html lang="en">
  <head>
  {% block head %}
        <title>
            {% block title %} {% endblock %} CSV Engine
        </title>
        
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        
        <link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('.static', filename='css/material.min.css')}}">
        <link rel="stylesheet" href="{{ url_for('.static', filename='css/style.css')}}">
        <!-- <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.blue_grey-deep_orange.min.css" />  -->
        
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{{ url_for('.static', filename='js/material.min.js')}}"></script>
        
        <style>
            {% block style %}
            {% endblock %}
        </style>
    {% endblock %}
  </head>
    <body class="mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
        <!-- Always shows a header, even in smaller screens. -->
        <div class="mdl-layout mdl-js-layout ">
            <header class="mdl-layout__header">
                <div class="mdl-layout__header-row">
                <!-- Title -->
                    <span class="mdl-layout-title">CSV Engine</span>
                    <!-- Add spacer, to align navigation to the right -->
                    <div class="mdl-layout-spacer"></div>
                    <!-- Navigation. We hide it in small screens. -->
                    <nav class="mdl-navigation mdl-layout--large-screen-only">
                        <!--  this needs to go to the backend -->
                        {% set active_page = active_page| default('index') -%}
                        
                        {% for href, id, caption in navigation_bar %}
                        <a class="mdl-navigation__link  {% if id == active_page %} is-active {% endif%}" href="{{ url_for(href) }}">       
                            {{ caption|e }}
                        </a>
                        {% endfor %}
                    </nav>
                </div>
            </header>
            <div class="mdl-layout__drawer">
                <span class="mdl-layout-title">CSV Engine</span>
                <nav class="mdl-navigation">
                    {% set active_page = active_page|default('index') -%}
                    {% for href, id, caption in navigation_bar %}
                    <a class="mdl-navigation__link mdl-layout__tab {% if id == active_page %} is-active {% endif%}" href="{{ url_for(href) }}">
                        {{ caption|e }}
                    </a>
                    {% endfor %}
                </nav>
            </div>
  
            <main class="mdl-layout__content" style="flex: 1 0 auto;">
                <div class="page-content">
                {% block content %}
    
                {% endblock %}
                </div>
            </main>
    
            <footer class="mdl-mini-footer">
                <div class="mdl-mini-footer__left-section">
                    <div class="mdl-logo">CSV Engine</div>
                    <ul class="mdl-mini-footer__link-list">
                        <li>
                            <a href="{{ url_for('privacy') }}">Privacy & Terms</a>
                        </li>
                    </ul>
                </div>
            </footer>
        </div>

        <script>
        {% block script %}
    
        {% endblock %}
        </script>
    </body>
</html>

csvengine/templates/csv_clean.html
{% extends "base.html" %}

{% import 'forms.html' as forms %}
  
{% set active_page = "csvclean" -%}

{% block title %}CSV Clean Submit -{% endblock %}

{% block content %}
  <div class="mdl-grid ce-wide-card">
    <div class="mdl-cell mdl-cell--2-col"></div>
    <div class="mdl-cell mdl-cell--8-col">
        {{ forms.submit('CSV Clean - Submit', 'csv.csvclean', 'clean my csv') }}
    </div>
</div>
{% endblock %}

{% block script %}
    {{ forms.js() }}
{% endblock %}

csvengine/templates/csv_clean_results.html
{% extends "base.html" %}
{% import 'table_factory.html' as tFactory %}
{% import 'forms.html' as forms %}

{% block title %}CSV Clean Results -{% endblock %}  
{% set active_page = "csvclean" -%}

{% block style %}
    
   {{ tFactory.tableCSS()}}

{% endblock %}


{% block content %}

    <div class="mdl-grid">
        <div class="mdl-cell  mdl-cell--1-col"></div>
        <div class="mdl-cell  mdl-cell--10-col">
            <div style="width:100%">
            {{tFactory.table_fromData(data, 'download', url_for('datacache.get_cleand_file')+'?fileID='+data.fileID)}}
            </div>
            
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ tFactory.tableJS() }}
{% endblock %}

csvengine/templates/csvm_editor.html
{% extends "base.html" %}
{% import 'forms.html' as forms %}
  
{% set active_page = "csvmval" -%}


{% block title %}CSV Validate -{% endblock %}



{% block content %}
  <div class="mdl-grid ce-wide-card">
    <div class="mdl-cell mdl-cell--2-col"></div>
    <div class="mdl-cell mdl-cell--8-col">
        <div class=" mdl-card mdl-shadow--2dp">
                  {{ forms.submit('CSV MetaData Editor - Submit', 'csvm.csvmeditor', 'Create Meta Data') }}
        </div>
    </div>

    <div class="mdl-cell mdl-cell--4-col mdl-cell--2-col-tablet">&nbsp;</div>
</div>
{% endblock %}

{% block script %}
 {{ forms.js()}}
{% endblock %}

csvengine/templates/csvm_editor_result.html
{% extends "base.html" %} 

{% import 'csvm_forms.html' as forms %}

{% block title %}CSV MetaData Editor -{% endblock %}
{% set active_page = "csvmeditor" -%}

{% block style %}
    div.tablewrapper {
  width: 100%;
  
  overflow: scroll;
}

table.column{
max-width:100%;
}
.mdl-textfield{
    width:100%;
}
.1showhide{
   position: relative;
   top: 35px;
   left: -12px;
   transform: translate(0px, -28px);
   z-index: 900;
}

{% endblock %}


{% block content %}

<div class="mdl-grid">
     <!-- Your content goes here -->
    <div class=" mdl-cell mdl-cell--1-col "></div>
    <div class="mdl-card mdl-cell mdl-cell--10-col mdl-shadow--4dp">
    <form action="{{ url_for('csvm.createcsvm_service') }}" method=post id="form">
        <div class="mdl-card__title mdl-card--border">
            <div>
                <div class="mdl-card__title-text ">
                    <a href="#">test.csv</a>
                </div>
                <div class="mdl-card__subtitle-text " > </div>
            </div>
        </div>
        <div class="mdl-card__supporting-text mdl-grid">
            <div class="mdl-cell mdl-cell--12-col " >
                <div class="mdl-color--primary mdl-color-text--accent">
					<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--icon mdl-button--colored showhide btn-showhide" id="tt3" type="button">
					    <i class="material-icons">expand_more</i>
					</button>
                    DATA
                    <div class="mdl-tooltip" for="tt3"> Preview <br>(10 rows)</div>
                </div>
                <div class="show" style="display:none;">
                    <label for="switch1" class="mdl-switch mdl-js-switch mdl-js-ripple-effect">
                        <input type="checkbox" id="switch1" class="mdl-switch__input" checked>
                        <span class="mdl-switch__label" id="label">Table Preview</span>
                        <div class="mdl-tooltip" for="label"> Preview <br>(10 rows)</div>
                    </label>
                    <div class="tablewrapper table">
						<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp full-width">
						    <thead>
						        <tr > {% for header in data.table.sample[0] %}
						            <th>{{header}}</th>
						        {% endfor %}</tr>
						    </thead>
						    <tbody> {% for row in data.table.sample %}
                                {% if loop.index != 1 and loop.index <= 10 %}
						            <tr>
						                {% for value in row %}
						                    <td>{{value}}</td>
						                {% endfor %}
						            </tr>
                                {% endif  %}
						    {% endfor %} </tbody>

						</table>
                    </div><!--  end tablewrappe -->

                    <div class="raw" style="display:none;">
                        <pre style="height:300px; overflow-y:auto;">{{ data.orig }}</pre>
                    </div>
                </div>
            </div>
        </div>
        <div class="mdl-card__supporting-text mdl-grid">
            <div class="mdl-cell mdl-cell--12-col">
                <div class="mdl-color--primary mdl-color-text--accent">
                 <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--icon mdl-button--colored showhide btn-showhide" id="tt4" type="button">
                     <i class="material-icons">expand_more</i>
                 </button>
                    METADATA
                    <div class="mdl-tooltip" for="tt4"> Preview <br>(5 rows)</div>
                </div>
                <div class=" show" >
                    <div class="mdl-tabs mdl-js-tabs">
                        <div class="mdl-tabs__tab-bar">
                            <a href="#tab1-panel" class="mdl-tabs__tab is-active">Table Description</a>
                            <a href="#tab2-panel" class="mdl-tabs__tab">Column Description</a>
                            <a href="#tab3-panel" class="mdl-tabs__tab">Dialect Description</a>
                        </div>
                        <div class="mdl-tabs__panel is-active" id="tab1-panel">
                            {{forms.tableDescription(data)}}
                        </div>
                        <div class="mdl-tabs__panel " id="tab2-panel">
                            {{forms.columnEditor(data)}}
                        </div>
                        <div class="mdl-tabs__panel" id="tab3-panel">
                            {{forms.dialectDescription(data)}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <button class="mdl-button mdl-button--raised mdl-button--colored mdl-js-button mdl-js-ripple-effect" >download metadata file</button>
            </div>
            <div class="mdl-card__menu">
                <span>{{ data.rows }} rows</span>
                <span>{{ data.cols }} cols</span>
            </div>
        </div>
    </form>
    </div>
</div>
    
    
{% endblock %}
{% block script %}
   
      $(".btn-showhide").click(function(){
        table = $(this).parent().siblings(".show")
        table.toggle()
        if (table.is(":visible")){
            $(this).find('i').text('expand_less')
        }else{
            $(this).find('i').text('expand_more')
        }
    });
    

    $(".mdl-switch__input").change(function(){
        if ($(this).is(':checked')) {

            table = $(this).parent().siblings(".table").show()
            $(this).siblings(".mdl-switch__label").text("Table Preview")

            raw = $(this).parent().siblings(".raw").hide()

        }
        else{
            table = $(this).parent().siblings(".table").hide()
            $(this).siblings(".mdl-switch__label").text("Raw Content")
            raw = $(this).parent().siblings(".raw").show()
            }

    });
    
    $(".table_metadata").on('change', function(){
        
        var v = $(this).val();
        var p= $(this).siblings("input")
        if ( v == "date" ){
            p.show();
            p.attr('placeholder' ,"e.g. M/d/yyyy");
        } else if ( v == "dateTime" || v == "dateTimeStamp"){
            p.show();
            p.attr('placeholder' ,"e.g. yyyy-MM-ddTHH:mm:ss");
        } else {
            p.hide();
        }
    })
    {% endblock %}
  

csvengine/templates/csvm_val.html
{% extends "base.html" %}
{% import 'forms.html' as forms %}
  
{% set active_page = "csvmval" -%}


{% block title %}CSV Validate -{% endblock %}



{% block content %}
  <div class="mdl-grid ce-wide-card">
    <div class="mdl-cell mdl-cell--3-col"></div>
    <div class="mdl-cell mdl-cell--6-col">
        <div class=" mdl-card mdl-shadow--2dp">
                  {{ forms.submit('CSV Validation - Submit', 'csvmval', 'validate my csv') }}
        </div>
    </div>

    <div class="mdl-cell mdl-cell--4-col mdl-cell--2-col-tablet">&nbsp;</div>
</div>
        
    
     <!-- Your content goes here -->
         
 <!-- 
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--1-col"></div>
            <div class="mdl-cell mdl-cell--10-col">
                <h4>Table recommendation</h4>
            </div>
        </div>
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--4-col"></div>
            <div class="mdl-cell mdl-cell--6-col">
            
                <form action="/submit" method=post enctype=multipart/form-data>
                    <input type="hidden" name="service" value="rec">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--file mdl-textfield--floating-label">
                        <input class="mdl-textfield__input"  type="text" id="url" name="url" />
                        <label class="mdl-textfield__label" for="sample3">URL...</label>
                        <div class="mdl-button mdl-button--primary mdl-button--icon mdl-button--file">
                            <i class="material-icons" >attach_file</i><input type="file" id="uploadBtn" name="uploadBtn">
                            <div class="mdl-tooltip" for="uploadBtn">Follow</div>
                        </div>
                    </div>
                    <button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">Recommend</button>
                </form>
            </div>
        </div>-->
{% endblock %}
{% block script %}

document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("url").value = this.files[0].name;
};


{% endblock %}

csvengine/templates/forms.html
{% macro submit(title, service, button) -%}
<div class="mdl-card mdl-shadow--2dp">
    <form action="{{ url_for('datacache.submit')}}" method=post enctype=multipart/form-data id="form">
        <div class="mdl-card__title" >
            <h2 class="mdl-card__title-text">{{ title }}</h2>
            
        </div>
        <div class="mdl-card__supporting-text">
            <input type="hidden" name="service" value="{{ service }}_service">
            <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
                <div class="mdl-tabs__tab-bar">
			      <a href="#urlSubmit" class="mdl-tabs__tab is-active">URL</a>
			      <a href="#fileSubmit" class="mdl-tabs__tab">File</a>
			      <a href="#textSubmit" class="mdl-tabs__tab">Copy & Paste</a>
                </div>

                <div class="mdl-tabs__panel is-active " id="urlSubmit">
			    <!-- URL submission -->
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
	                        <!-- pattern="(https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})" -->
	                        <input class="mdl-textfield__input" type="text" id="url" name='url' pattern="^$|(https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})"/>
		                   <label class="mdl-textfield__label">URL</label>
		                   <span class="mdl-textfield__error">Validating URL ...</span>
	                    </div>
                </div>
                <div class="mdl-tabs__panel mdl_grid" id="fileSubmit">
                <!--  File ID submission -->
                    
                    <div class="mdl-cell mdl-cell--12-col">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                        <input class="mdl-textfield__input" type="text" id="fileID" name='fileID' />
                        <label class="mdl-textfield__label">Existing File id</label>
                    </div>
                    <!--  file upload -->
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--file mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                        <input class="mdl-textfield__input"  type="text" id="Upload" placeholder="File upload" name="fileUpload" readonly/>
                        <div class="mdl-button mdl-button--primary mdl-button--icon mdl-button--file">
                            <i class="material-icons" >attach_file</i>
                            <input type="file" id="uploadBtn" name="uploadBtn">
                                <div class="mdl-tooltip" for="uploadBtn">Upload</div>
                        </div>
                    </div>
                    </div>
                </div>
                
                <div class="mdl-tabs__panel" id="textSubmit">
                    <!--  copy paste -->
                    <div class="mdl-textfield mdl-js-textfield  mdl-cell mdl-cell--12-col">
                        <textarea class="mdl-textfield__input" type="text" rows= "3" id="textUpload" cols="80" name="textUpload"></textarea>
                        <label class="mdl-textfield__label" for="sample5">CSV lines...</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <div class="mdl-grid">
	            <div class="mdl-cell mdl-cell--6-col">
	                <button class="mdl-button mdl-button--raised mdl-button--colored mdl-js-button mdl-js-ripple-effect" id="submit">{{ button }}</button>
	             </div>
	             <div  class="mdl-cell mdl-cell--6-col">
	                <label for="chkbox1" class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect">
	                    <input type="checkbox" id="chkbox1" name="check" class="mdl-checkbox__input">
	                    <span class="mdl-checkbox__label">Please, do not cache my data!</span>
	                </label>
	            </div>
            </div>
        </div>
    </form>
</div>    
{%- endmacro %}

{% macro js() -%}
    document.getElementById("uploadBtn").onchange = function () {
        document.getElementById("Upload").value = this.files[0].name;
    };
    $("#form").submit(function(e) {
        
        emptyInput = $('input:text').filter(function() { return $(this).val() == ""; }).length
        if( !$("#textUpload").val() && emptyInput ==3) {
            alert("No input specified")
            return false
        }
        if( emptyInput < 2 || ( emptyInput != 3 && $("#textUpload").val() ) )  {
            alert('Multiple input fields are provided');
            return false;
        }
        return true;
        
    })

{%- endmacro %}

csvengine/templates/privacy.html
{% extends "base.html" %} {% block title %}Portal List{% endblock %}  
{% set active_page = "index" -%}
{% block content %}
     <!-- Your content goes here -->
         
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--1-col"></div>
            <div class="mdl-cell mdl-cell--10-col">
                <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
                    <div class="mdl-card mdl-cell mdl-cell--12-col">
                    <div class="mdl-card__title mdl-color--blue-grey-300">
                        <h2 class="mdl-card__title-text">How Your Data is Stored</h2>
                    </div>
                        <div class="mdl-card__supporting-text">
                            The CSVEngine stores by default user submitted files or the content of URLs.
                            We provide a input flag to avoid caching of your submitted data.
                        </div>
                    </div>
        
                </section>
            </div>
        </div>
       

  
 {% endblock %}